name = "zapychan-org"
compatibility_date = "2025-01-20"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "zapychan-views"
database_id = "25fbbe59-1ea5-4f18-8826-feabddd2f612"
